# Generated by Django 5.0.2 on 2024-03-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Risk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("creation", models.DateTimeField(auto_now_add=True)),
                ("update", models.DateTimeField(auto_now=True)),
                ("likelyhood", models.PositiveIntegerField()),
                ("impact", models.PositiveIntegerField()),
                (
                    "treatment",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Mitigate"), ("T", "Transfer"), ("A", "Avoid"), ("C", "Accept")],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("confidentiality", models.BooleanField(default=False)),
                ("integrity", models.BooleanField(default=False)),
                ("availability", models.BooleanField(default=False)),
                ("custom_id", models.CharField(max_length=20)),
            ],
        ),
    ]
