# Generated by Django 5.0.2 on 2024-03-16 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("risk", "0004_alter_risk_treatment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupPermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("view_title", models.BooleanField(default=False)),
                ("edit_title", models.BooleanField(default=False)),
                ("view_description", models.BooleanField(default=False)),
                ("edit_description", models.BooleanField(default=False)),
                ("remove", models.BooleanField(default=False)),
                ("manage_permission", models.BooleanField(default=False)),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="auth.group")),
                ("risk", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="risk.risk")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserPermission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("view_title", models.BooleanField(default=False)),
                ("edit_title", models.BooleanField(default=False)),
                ("view_description", models.BooleanField(default=False)),
                ("edit_description", models.BooleanField(default=False)),
                ("remove", models.BooleanField(default=False)),
                ("manage_permission", models.BooleanField(default=False)),
                ("risk", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="risk.risk")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
