# Generated by Django 5.0.2 on 2024-03-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0006_risk_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouppermission",
            name="assign_owner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userpermission",
            name="assign_owner",
            field=models.BooleanField(default=False),
        ),
    ]
