# Generated by Django 5.0.2 on 2024-03-24 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0007_grouppermission_assign_owner_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userpermission",
            name="risk",
        ),
        migrations.RemoveField(
            model_name="userpermission",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="risk",
            options={"permissions": (("view", "edit"),)},
        ),
        migrations.DeleteModel(
            name="GroupPermission",
        ),
        migrations.DeleteModel(
            name="UserPermission",
        ),
    ]
