# Generated by Django 5.0.2 on 2024-03-24 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0008_remove_userpermission_risk_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="risk",
            options={},
        ),
    ]
