# Generated by Django 5.0.2 on 2024-03-11 00:32

import archive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archive", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archive",
            name="content",
            field=models.FileField(upload_to=archive.models.hash_upload),
        ),
    ]
